# Generated by Django 2.2.3 on 2020-06-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20200617_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='english_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='japanese_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
